//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace индивид
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ветеринарная_клиникаEntities : DbContext
    {
        private static ветеринарная_клиникаEntities _context;
        public static ветеринарная_клиникаEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ветеринарная_клиникаEntities();
            }
            return _context;
        }
        public ветеринарная_клиникаEntities()
            : base("name=ветеринарная_клиникаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<вид_пациента> вид_пациента { get; set; }
        public virtual DbSet<врачи> врачи { get; set; }
        public virtual DbSet<город> город { get; set; }
        public virtual DbSet<диагноз> диагноз { get; set; }
        public virtual DbSet<клиент> клиент { get; set; }
        public virtual DbSet<лечение> лечение { get; set; }
        public virtual DbSet<пациент> пациент { get; set; }
        public virtual DbSet<пол_пациента> пол_пациента { get; set; }
        public virtual DbSet<пользователь> пользователь { get; set; }
        public virtual DbSet<порода_пациента> порода_пациента { get; set; }
        public virtual DbSet<роли> роли { get; set; }
        public virtual DbSet<специализация> специализация { get; set; }
        public virtual DbSet<страна> страна { get; set; }
        public virtual DbSet<улица> улица { get; set; }
        public virtual DbSet<услуга> услуга { get; set; }
    }
}
