//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace индивид
{
    using System;
    using System.Collections.Generic;
    
    public partial class врачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public врачи()
        {
            this.лечение = new HashSet<лечение>();
        }
    
        public int код_врача { get; set; }
        public string ф_врача { get; set; }
        public string и_врача { get; set; }
        public string о_врача { get; set; }
        public int код_специализации { get; set; }
        public System.DateTime дата_принятия_на_работу { get; set; }
    
        public virtual специализация специализация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<лечение> лечение { get; set; }
    }
}
