//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace индивид
{
    using System;
    using System.Collections.Generic;
    
    public partial class клиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public клиент()
        {
            this.пациент = new HashSet<пациент>();
        }
    
        public int код_клиента { get; set; }
        public string ф_клиента { get; set; }
        public string и_клиента { get; set; }
        public string о_клиента { get; set; }
        public string телефон { get; set; }
        public int код_страны { get; set; }
        public string e_mail { get; set; }
        public int код_города { get; set; }
        public int код_улицы { get; set; }
        public string номер_дома { get; set; }
        public int номер_квартиры { get; set; }
    
        public virtual город город { get; set; }
        public virtual страна страна { get; set; }
        public virtual улица улица { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<пациент> пациент { get; set; }
    }
}
