//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace индивид
{
    using System;
    using System.Collections.Generic;
    
    public partial class пациент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пациент()
        {
            this.лечение = new HashSet<лечение>();
        }
    
        public int код_пациента { get; set; }
        public int код_клиента { get; set; }
        public string кличка { get; set; }
        public int код_вида { get; set; }
        public int код_породы { get; set; }
        public string дата_рождения { get; set; }
        public string вес { get; set; }
        public int код_пола_пациента { get; set; }
    
        public virtual вид_пациента вид_пациента { get; set; }
        public virtual клиент клиент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<лечение> лечение { get; set; }
        public virtual пол_пациента пол_пациента { get; set; }
        public virtual порода_пациента порода_пациента { get; set; }
    }
}
