//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace индивид
{
    using System;
    using System.Collections.Generic;
    
    public partial class услуга
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public услуга()
        {
            this.лечение = new HashSet<лечение>();
        }

        public string GetColor
        {
            get
            {
                if (действующая_скидка > 0)
                    return "#98FB98";
                else
                    return "#FFF";
            }
        }

        public string GetVisilibility
        {
            get
            {
                if (действующая_скидка == 0)
                    return "Collapsed";
                else
                    return "Visible";
            }
        }
        public string TotalPrice
        {
            get
            {
                double p = (double)(стоимость - стоимость * Convert.ToDouble(действующая_скидка) / 100);
                return $"{p:F2} рублей за {длительность} минут";
            }
        }
        public int код_услуги { get; set; }
        public string наименование_услуги { get; set; }
        public double стоимость { get; set; }
        public Nullable<decimal> действующая_скидка { get; set; }
        public Nullable<int> длительность { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<лечение> лечение { get; set; }
    }
}
